language: cpp
os: linux
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - g++-8-multilib

matrix:
  include:
    - compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - compiler: clang

before_install:
  - eval "${MATRIX_EVAL}"
  - $CXX --version

script:
  - cd ./build
  - make debug=1 && make
  - ./bin/debug/$CC/ut

notifications:
  slack:
    on_success: never
    on_failure: never
