language: cpp
os: linux
dist: bionic

compiler:
  - clang
  - gcc

before_install:
  - $CXX --version

script:
  - cd ./build
  - make debug=1 && make
  - ./bin/debug/$CC/ut

notifications:
  slack:
    on_success: never
    on_failure: never
