language: cpp
os: linux
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

matrix:
  include:
    - compiler: gcc
      env:
        - CXX=g++-8
        - CX=g++-8
        - CC=gcc-8

    - compiler: clang
      env:
        - CXX=clang++
        - CX=clang++
        - CC=clang

before_install:
  - $CXX --version

script:
  - cd ./build
  - make debug=1 && make
  - ./bin/debug/$CC/ut

notifications:
  slack:
    on_success: never
    on_failure: never
