language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9', 'g++-4.9-multilib', 'linux-libc-dev']
      env:
        - CXX=g++-4.9
        - CX=g++-4.9
        - CC=gcc-4.9

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['clang-3.4', 'g++-4.8', 'g++-4.8-multilib', 'linux-libc-dev']
      env:
        - CXX=clang++
        - CX=clang++
        - CC=clang

install:
  - $CX --version
  - ln -sv /usr/include/asm-generic /usr/include/asm

script:
  - cd ./build
  - make debug=1 && make
  - ./bin/debug/$CC/ut

notifications:
  slack:
    on_success: never
    on_failure: never
